name: Build a Dataset
on: 
  workflow_dispatch:
    inputs:
        dataset:
          description: 'Dataset file'
          required: true
        seed:
          description: 'Seed'
          required: true
          default: '2022'
        branch:
          description: 'Branch to checkout'     
          required: true
          default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "data/requirements.txt"
      - name: Run dataset construction
        working-directory: ./data
        run: ls && python gen-${{ github.event.inputs.dataset }}.py ${{ github.event.inputs.seed }}
      - name: Upload to gcloud
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJ_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD }}
        with:
          args: cp -r datasets/${{ github.event.inputs.dataset }}/* gs://${{ secrets.DATA_PLATFORM }}/${{ github.event.inputs.dataset }}-git
          cli: gsutil