name: Deploy web to production
on:
    push:
        branches:
            - "web_page"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout branch
              uses: actions/checkout@v2
              with:
                  ref: "web_page"
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install python dependencies
              uses: py-actions/py-dependency-install@v3
              with:
                  path: ".ci/requirements.txt"
            - uses: actions/cache@v2
              name: Install Prettier
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Run style
              run: chmod +x style.sh && ./style.sh
            - name: Run unit tests
              run: chmod +x unittests.sh && ./unittests.sh
            - name: Notify deploy server
              run: 'curl -X POST ${{ secrets.PROD_URL }} -d ''{"ref": "refs/heads/web_page"}'''
