name: Deploy to Deta
on:
  push:
    branches:
      - 'web_page'
  workflow_dispatch:
      
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
        with:
          ref: 'web_page'
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'web' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: 'sum-everything' #Optional: Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project-dir: 'sumWeb' #Optional: directory to be deployed on Deta. Default is the root "." 
